### ISSUE TITLE
Issue Migrating Old DB

### ISSUE THREAD

**Issue by BrodyStone21** [crazy-max/docker-flarum#114]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/docker-flarum/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm trying to migrate from a hosting provider to self hosted through Docker. I'm trying to migrate the DB but am having issues. I can connect and stuff just fine, but I'm getting the following error:

```
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-fix-perms.sh: executing...
Fixing perms...
[cont-init.d] 02-fix-perms.sh: exited 0.
[cont-init.d] 03-config.sh: executing...
Setting timezone to America/Indianapolis...
Setting PHP-FPM configuration...
Setting PHP INI configuration...
Setting OpCache configuration...
Setting Nginx configuration...
Initializing files and folders...
cp: can't create '/data/assets': File exists
cp: can't create '/data/storage': File exists
Permissions already fixed in /data/assets
Permissions already fixed in /data/extensions
Permissions already fixed in /data/storage
Permissions already fixed in /opt/flarum/vendor
Checking parameters...
Checking database connection...
Waiting 60s for database to be ready...
Database ready!
Creating Flarum config file...
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flarum_settings' doesn't exist in /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
Stack trace:
#0 /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(82): PDO->prepare()
#1 /opt/flarum/vendor/illuminate/database/Connection.php(368): Doctrine\DBAL\Driver\PDOConnection->prepare()
#2 /opt/flarum/vendor/illuminate/database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /opt/flarum/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#4 /opt/flarum/vendor/illuminate/database/Connection.php(359): Illuminate\Database\Connection->run()
#5 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2413): Illuminate\Database\Connection->select()
#6 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2626): Illuminate\Database\Query\Builder->runSelect()
#7 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#8 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2622): Illuminate\Database\Query\Builder->onceWithColumns()
#9 /opt/flarum/vendor/flarum/core/src/Settings/DatabaseSettingsRepository.php(25): Illuminate\Database\Query\Builder->pluck()
#10 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(30): Flarum\Settings\DatabaseSettingsRepository->all()
#11 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(42): Flarum\Settings\MemoryCacheSettingsRepository->all()
#12 /opt/flarum/vendor/flarum/core/src/Settings/DefaultSettingsRepository.php(30): Flarum\Settings\MemoryCacheSettingsRepository->get()
#13 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(401): Flarum\Settings\DefaultSettingsRepository->get()
#14 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(140): Flarum\Extension\ExtensionManager->getEnabled()
#15 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(371): Flarum\Extension\ExtensionManager->getExtensions()
#16 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(389): Flarum\Extension\ExtensionManager->getEnabledExtensions()
#17 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#18 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#19 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#20 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#21 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#22 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#23 /opt/flarum/vendor/flarum/core/src/Console/Server.php(32): Flarum\Foundation\InstalledSite->bootApp()
#24 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#25 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flarum_settings' doesn't exist in /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(87): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /opt/flarum/vendor/illuminate/database/Connection.php(368): Doctrine\DBAL\Driver\PDOConnection->prepare()
#2 /opt/flarum/vendor/illuminate/database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /opt/flarum/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#4 /opt/flarum/vendor/illuminate/database/Connection.php(359): Illuminate\Database\Connection->run()
#5 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2413): Illuminate\Database\Connection->select()
#6 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2626): Illuminate\Database\Query\Builder->runSelect()
#7 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#8 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2622): Illuminate\Database\Query\Builder->onceWithColumns()
#9 /opt/flarum/vendor/flarum/core/src/Settings/DatabaseSettingsRepository.php(25): Illuminate\Database\Query\Builder->pluck()
#10 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(30): Flarum\Settings\DatabaseSettingsRepository->all()
#11 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(42): Flarum\Settings\MemoryCacheSettingsRepository->all()
#12 /opt/flarum/vendor/flarum/core/src/Settings/DefaultSettingsRepository.php(30): Flarum\Settings\MemoryCacheSettingsRepository->get()
#13 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(401): Flarum\Settings\DefaultSettingsRepository->get()
#14 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(140): Flarum\Extension\ExtensionManager->getEnabled()
#15 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(371): Flarum\Extension\ExtensionManager->getExtensions()
#16 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(389): Flarum\Extension\ExtensionManager->getEnabledExtensions()
#17 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#18 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#19 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#20 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#21 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#22 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#23 /opt/flarum/vendor/flarum/core/src/Console/Server.php(32): Flarum\Foundation\InstalledSite->bootApp()
#24 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#25 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flarum_settings' doesn't exist (SQL: select `value`, `key` from `flarum_settings`) in /opt/flarum/vendor/illuminate/database/Connection.php:712
Stack trace:
#0 /opt/flarum/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/flarum/vendor/illuminate/database/Connection.php(359): Illuminate\Database\Connection->run()
#2 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2413): Illuminate\Database\Connection->select()
#3 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2626): Illuminate\Database\Query\Builder->runSelect()
#4 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2622): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /opt/flarum/vendor/flarum/core/src/Settings/DatabaseSettingsRepository.php(25): Illuminate\Database\Query\Builder->pluck()
#7 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(30): Flarum\Settings\DatabaseSettingsRepository->all()
#8 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(42): Flarum\Settings\MemoryCacheSettingsRepository->all()
#9 /opt/flarum/vendor/flarum/core/src/Settings/DefaultSettingsRepository.php(30): Flarum\Settings\MemoryCacheSettingsRepository->get()
#10 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(401): Flarum\Settings\DefaultSettingsRepository->get()
#11 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(140): Flarum\Extension\ExtensionManager->getEnabled()
#12 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(371): Flarum\Extension\ExtensionManager->getExtensions()
#13 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(389): Flarum\Extension\ExtensionManager->getEnabledExtensions()
#14 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#15 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#16 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#17 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#18 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#19 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#20 /opt/flarum/vendor/flarum/core/src/Console/Server.php(32): Flarum\Foundation\InstalledSite->bootApp()
#21 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#22 {main}
  thrown in /opt/flarum/vendor/illuminate/database/Connection.php on line 712
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flarum_settings' doesn't exist in /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:82
Stack trace:
#0 /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(82): PDO->prepare()
#1 /opt/flarum/vendor/illuminate/database/Connection.php(368): Doctrine\DBAL\Driver\PDOConnection->prepare()
#2 /opt/flarum/vendor/illuminate/database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /opt/flarum/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#4 /opt/flarum/vendor/illuminate/database/Connection.php(359): Illuminate\Database\Connection->run()
#5 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2413): Illuminate\Database\Connection->select()
#6 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2626): Illuminate\Database\Query\Builder->runSelect()
#7 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#8 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2622): Illuminate\Database\Query\Builder->onceWithColumns()
#9 /opt/flarum/vendor/flarum/core/src/Settings/DatabaseSettingsRepository.php(25): Illuminate\Database\Query\Builder->pluck()
#10 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(30): Flarum\Settings\DatabaseSettingsRepository->all()
#11 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(42): Flarum\Settings\MemoryCacheSettingsRepository->all()
#12 /opt/flarum/vendor/flarum/core/src/Settings/DefaultSettingsRepository.php(30): Flarum\Settings\MemoryCacheSettingsRepository->get()
#13 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(401): Flarum\Settings\DefaultSettingsRepository->get()
#14 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(140): Flarum\Extension\ExtensionManager->getEnabled()
#15 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(371): Flarum\Extension\ExtensionManager->getExtensions()
#16 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(389): Flarum\Extension\ExtensionManager->getEnabledExtensions()
#17 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#18 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#19 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#20 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#21 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#22 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#23 /opt/flarum/vendor/flarum/core/src/Console/Server.php(32): Flarum\Foundation\InstalledSite->bootApp()
#24 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#25 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flarum_settings' doesn't exist in /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /opt/flarum/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(87): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /opt/flarum/vendor/illuminate/database/Connection.php(368): Doctrine\DBAL\Driver\PDOConnection->prepare()
#2 /opt/flarum/vendor/illuminate/database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /opt/flarum/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#4 /opt/flarum/vendor/illuminate/database/Connection.php(359): Illuminate\Database\Connection->run()
#5 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2413): Illuminate\Database\Connection->select()
#6 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2626): Illuminate\Database\Query\Builder->runSelect()
#7 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#8 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2622): Illuminate\Database\Query\Builder->onceWithColumns()
#9 /opt/flarum/vendor/flarum/core/src/Settings/DatabaseSettingsRepository.php(25): Illuminate\Database\Query\Builder->pluck()
#10 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(30): Flarum\Settings\DatabaseSettingsRepository->all()
#11 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(42): Flarum\Settings\MemoryCacheSettingsRepository->all()
#12 /opt/flarum/vendor/flarum/core/src/Settings/DefaultSettingsRepository.php(30): Flarum\Settings\MemoryCacheSettingsRepository->get()
#13 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(401): Flarum\Settings\DefaultSettingsRepository->get()
#14 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(140): Flarum\Extension\ExtensionManager->getEnabled()
#15 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(371): Flarum\Extension\ExtensionManager->getExtensions()
#16 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(389): Flarum\Extension\ExtensionManager->getEnabledExtensions()
#17 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#18 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#19 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#20 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#21 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#22 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#23 /opt/flarum/vendor/flarum/core/src/Console/Server.php(32): Flarum\Foundation\InstalledSite->bootApp()
#24 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#25 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'flarum.flarum_settings' doesn't exist (SQL: select `value`, `key` from `flarum_settings`) in /opt/flarum/vendor/illuminate/database/Connection.php:712
Stack trace:
#0 /opt/flarum/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 /opt/flarum/vendor/illuminate/database/Connection.php(359): Illuminate\Database\Connection->run()
#2 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2413): Illuminate\Database\Connection->select()
#3 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2626): Illuminate\Database\Query\Builder->runSelect()
#4 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2936): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /opt/flarum/vendor/illuminate/database/Query/Builder.php(2622): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /opt/flarum/vendor/flarum/core/src/Settings/DatabaseSettingsRepository.php(25): Illuminate\Database\Query\Builder->pluck()
#7 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(30): Flarum\Settings\DatabaseSettingsRepository->all()
#8 /opt/flarum/vendor/flarum/core/src/Settings/MemoryCacheSettingsRepository.php(42): Flarum\Settings\MemoryCacheSettingsRepository->all()
#9 /opt/flarum/vendor/flarum/core/src/Settings/DefaultSettingsRepository.php(30): Flarum\Settings\MemoryCacheSettingsRepository->get()
#10 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(401): Flarum\Settings\DefaultSettingsRepository->get()
#11 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(140): Flarum\Extension\ExtensionManager->getEnabled()
#12 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(371): Flarum\Extension\ExtensionManager->getExtensions()
#13 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionManager.php(389): Flarum\Extension\ExtensionManager->getEnabledExtensions()
#14 /opt/flarum/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#15 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#16 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#17 /opt/flarum/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#18 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#19 /opt/flarum/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#20 /opt/flarum/vendor/flarum/core/src/Console/Server.php(32): Flarum\Foundation\InstalledSite->bootApp()
#21 /opt/flarum/flarum(24): Flarum\Console\Server->listen()
#22 {main}
  thrown in /opt/flarum/vendor/illuminate/database/Connection.php on line 712
[cont-init.d] 03-config.sh: exited 255.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I tried looking on the Flarum forum about similar issues from about 4 years ago, and they suggested running `php flarum migrate` but seeing as how the container crashes out, I'm unable to do that.

### Expected behaviour

Flarum uses other DB normally.

### Actual behaviour

Flarum does not use other DB normally.

### Steps to reproduce

1. Export old DB from hosting provider
2. Import old DB into MariaDB 10 and your Flarum version
3. Attempt to start Flarum
4. Check logs
5. Be sad

### Docker info

```text
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 44
  Running: 28
  Paused: 0
  Stopped: 16
 Images: 94
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-118-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.678GiB
 Name: ubuntu
 ID: 099c2ac3-efe6-40de-8c63-cc60b883df7d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
services:
  flarum:
    image: crazymax/flarum:latest
    container_name: flarum
    env_file:
      - /home/ubuntu/.config/flarum/flarum.env
    environment:
      - TZ=America/Indianapolis
      - PUID=1000
      - PGID=1000
      - DB_HOST=flarum_db
      - DB_NAME=flarum
      - DB_USER=flarum
      - DB_PASSWORD=FlarumDBPasswd#21
      - FLARUM_BASE_URL=http://192.168.1.2:8000
    volumes:
      - /home/ubuntu/.config/flarum/data:/data
    ports:
      - 8000:8000/tcp
    depends_on:
      - flarum_db
    restart: unless-stopped
  flarum_db:
    image: mariadb:10
    container_name: flarum_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=RootDBPasswd#21!
      - MYSQL_DATABASE=temp
      - MYSQL_USER=temp
      - MYSQL_PASSWORD=FlarumDBPasswd#21
    volumes:
      - /home/ubuntu/.config/flarum_db:/var/lib/mysql
  cloudflared_flarum:
    container_name: cloudflared_flarum
    restart: unless-stopped
    image: cloudflare/cloudflared:latest-amd64
    environment:
      - TUNNEL_DNS_UPSTREAM=127.0.0.1#5053,127.0.0.1#5053
      - TUNNEL_DNS_ADDRESS=0.0.0.0
    volumes:
      - /home/ubuntu/.config/cloudflared_flarum:/home/nonroot/.cloudflared/
    network_mode: host
    command:
      tunnel run flarum
  nginx_flarum:
    container_name: nginx_flarum
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 85:80
      - 81:81
      - 4443:443
    volumes:
      - /home/ubuntu/.config/nginx_flarum/data:/data
      - /home/ubuntu/.config/nginx_flarum/letsencrypt:/etc/letsencrypt
```
```


### Logs

```text
^
```

### Additional info

Please note the "temp" user in MariaDB was required. If I tried to connect with an empty /data volume, before creating a fresh install, it wouldn't work. I'm now trying to connect to the new DB, which I technically have, but I can't get it to work properly.

Any help is greatly appreciated. Please let me know if you require any additional information.

**Comment by eightysixed** [comment]
Have you tried `php flare migrate`?
